title: Programmer en Python
subtitle: Master 2 DUAS Unistra, 2019-2020
authors:
  - name: Matthieu Boileau
    email: matthieu.boileau@math.unistra.fr
  - name: Vincent Legoll
    email: vincentlegoll@gmail.com